/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is generated by scripts/embed-env-vars.js
 * Run `node scripts/embed-env-vars.js` to regenerate.
 * 
 * This file will be populated with environment variables at build time.
 */

export const embeddedEnv: Record<string, string | undefined> = {
  // Will be populated by embed-env-vars.js before build
};

export function getEmbeddedEnv(varName: string): string | undefined {
  return embeddedEnv[varName];
}

export function getGitHubToken(): string | undefined {
  return embeddedEnv.GITHUB_TOKEN || embeddedEnv.GH_TOKEN || embeddedEnv.VITE_GITHUB_TOKEN;
}
