import { TodoList } from './components/TodoList';

function App() {
  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#f5f5f5' }}>
      <div style={{ 
        backgroundColor: '#4CAF50', 
        color: 'white', 
        padding: '20px',
        textAlign: 'center'
      }}>
        <h1>🚀 Postgres Test App - Automated Setup</h1>
        <p>✅ Server auto-generated | ✅ Migrations auto-run | ✅ Full CRUD operations</p>
      </div>
      <TodoList />
      <div style={{ 
        textAlign: 'center', 
        padding: '20px', 
        color: '#666',
        fontSize: '14px'
      }}>
        <p>
          <strong>This entire app was auto-generated by AI!</strong>
        </p>
        <p>
          Database: Local Postgres | Schema: app_test_12345 | Port: 3001
        </p>
      </div>
    </div>
  );
}

export default App;

