name: Build and Release
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Configure Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Increment Version
        run: node scripts/increment-version.js

      - name: Push Version Bump
        run: |
          git add package.json
          git commit -m "Bump version [skip ci]"
          git push

      - name: Get Version
        id: get_version
        run: |
           $packageJson = Get-Content package.json -Raw | ConvertFrom-Json
           echo "NEW_VERSION=$($packageJson.version)" >> $env:GITHUB_ENV

      - name: Build / Make
        run: npm run make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to Public Repo
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.NEW_VERSION }}" 
          name: "v${{ env.NEW_VERSION }}"
          files: |
            out/make/squirrel.windows/x64/*.exe
            out/make/squirrel.windows/x64/RELEASES
            out/make/squirrel.windows/x64/*.nupkg
          repository: Applaa-Builder/applaa-releases
          token: ${{ secrets.RELEASE_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
